services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_TIMEOUT: ${DB_TIMEOUT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public/maintenance.html:/etc/nginx/html/maintenance.html
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  nginx:
