default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_DATABASE'] %>
  timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: cavelog_test

development:
  !!merge <<: *default

production:
  !!merge <<: *default
